repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        files: "^cromulant/.*"
        args: [--strict, --strict, --strict, cromulant/main.py]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    -   id: ruff
        name: ruff check
        entry: ruff check
        files: ^cromulant/
    -   id: ruff
        name: ruff format
        entry: ruff format
        files: ^cromulant/